services:
  app01:
    container_name: app01
    build: ./app/
    restart: unless-stopped
    environment:
      - APP_NAME=app01
      - ENV=development
    volumes:
      - ./app:/app
    networks:
      - app-network

  app02:
    container_name: app02
    build: ./app/
    restart: unless-stopped
    environment:
      - APP_NAME=app02
      - ENV=development
    volumes:
      - ./app:/app
    networks:
      - app-network

  nginx:
    container_name: nginx-web
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app01
      - app02
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
